name: Labeler
on:
  pull_request: { types: [ opened, edited, synchronize, reopened ] }

permissions:
  contents: read
  statuses: write
  checks: write
  pull-requests: write

jobs:
  apply-labels:
    runs-on: ubuntu-latest
    name: Apply
    steps: [ uses: fuxingloh/multi-labeler@v5 ]